# 03 Experiments

Запуск всех CP1-моделей и сохранение таблицы метрик в `models/metrics.csv`.

In [ ]:
from pathlib import Path
import sys

# Если ноутбук открыт из папки notebooks, поднимаемся на уровень выше.
PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

# Добавляем корень проекта в Python path.
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("PROJECT_ROOT:", PROJECT_ROOT)
print("src exists:", (PROJECT_ROOT / "src").exists())

In [3]:
from pathlib import Path
import pandas as pd

from src.modeling import load_dataset, train_experiments

df = load_dataset(Path('../data/processed/stepik_course_steps_processed.csv'))
metrics = train_experiments(df, Path('../models'))
metrics

c:\anaconda\Lib\site-packages\sklearn\impute\_base.py:555: UserWarning: Skipping features without any observed values: ['reviews_count' 'rating' 'sections_count' 'submissions_count'
 'videos_duration' 'unit_progress_weight' 'step_cost']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\anaconda\Lib\site-packages\sklearn\impute\_base.py:555: UserWarning: Skipping features without any observed values: ['reviews_count' 'rating' 'sections_count' 'submissions_count'
 'videos_duration' 'unit_progress_weight' 'step_cost']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\anaconda\Lib\site-packages\sklearn\impute\_base.py:555: UserWarning: Skipping features without any observed values: ['reviews_count' 'rating' 'sections_count' 'submissions_count'
 'videos_duration' 'unit_progress_weight' 'step_cost']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\anaconda\Lib\site-packages\sklearn\impute\_base.py:555: UserWarning: Skipping features without any observed values: ['reviews_count' 'rating' 'sections_count' 'submissions_count'
 'videos_duration' 'unit_progress_weight' 'step_cost']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\anaconda\Lib\site-packages\sklearn\impute\_base.py:555: UserWarning: Skipping features without any observed values: ['reviews_count' 'rating' 'sections_count' 'submissions_count'
 'videos_duration' 'unit_progress_weight' 'step_cost']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\anaconda\Lib\site-packages\sklearn\impute\_base.py:555: UserWarning: Skipping features without any observed values: ['reviews_count' 'rating' 'sections_count' 'submissions_count'
 'videos_duration' 'unit_progress_weight' 'step_cost']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\anaconda\Lib\site-packages\sklearn\impute\_base.py:555: UserWarning: Skipping features without any observed values: ['reviews_count' 'rating' 'sections_count' 'submissions_count'
 'videos_duration' 'unit_progress_weight' 'step_cost']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\anaconda\Lib\site-packages\sklearn\impute\_base.py:555: UserWarning: Skipping features without any observed values: ['reviews_count' 'rating' 'sections_count' 'submissions_count'
 'videos_duration' 'unit_progress_weight' 'step_cost']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\anaconda\Lib\site-packages\sklearn\impute\_base.py:555: UserWarning: Skipping features without any observed values: ['reviews_count' 'rating' 'sections_count' 'submissions_count'
 'videos_duration' 'unit_progress_weight' 'step_cost']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\anaconda\Lib\site-packages\sklearn\impute\_base.py:555: UserWarning: Skipping features without any observed values: ['reviews_count' 'rating' 'sections_count' 'submissions_count'
 'videos_duration' 'unit_progress_weight' 'step_cost']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\anaconda\Lib\site-packages\sklearn\impute\_base.py:555: UserWarning: Skipping features without any observed values: ['reviews_count' 'rating' 'sections_count' 'submissions_count'
 'videos_duration' 'unit_progress_weight' 'step_cost']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\anaconda\Lib\site-packages\sklearn\impute\_base.py:555: UserWarning: Skipping features without any observed values: ['reviews_count' 'rating' 'sections_count' 'submissions_count'
 'videos_duration' 'unit_progress_weight' 'step_cost']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
c:\anaconda\Lib\site-packages\sklearn\impute\_base.py:555: UserWarning: Skipping features without any observed values: ['reviews_count' 'rating' 'sections_count' 'submissions_count'
 'videos_duration' 'unit_progress_weight' 'step_cost']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

,model,split,rmse_log,mae_log,r2_log,rmse_learners,mae_learners
0,best:hist_gradient_boosting,test,1.364928,0.967064,0.474948,169.080830,52.918014
1,hist_gradient_boosting,val,1.030200,0.772590,0.434820,29.119448,12.982654
2,extra_trees,val,1.076512,0.865414,0.382862,28.527834,13.040401
3,random_forest,val,1.082582,0.858977,0.375883,27.807487,13.219982
4,ridge_alpha_10,val,1.416305,1.084965,-0.068213,32.624613,16.690600
5,ridge_alpha_1,val,1.418588,1.087659,-0.071660,32.573997,16.685407
6,dummy_median,val,1.736167,1.607452,-0.605193,30.561288,19.090106

In [4]:
metrics.sort_values(['split', 'rmse_log'])

,model,split,rmse_log,mae_log,r2_log,rmse_learners,mae_learners
0,best:hist_gradient_boosting,test,1.364928,0.967064,0.474948,169.080830,52.918014
1,hist_gradient_boosting,val,1.030200,0.772590,0.434820,29.119448,12.982654
2,extra_trees,val,1.076512,0.865414,0.382862,28.527834,13.040401
3,random_forest,val,1.082582,0.858977,0.375883,27.807487,13.219982
4,ridge_alpha_10,val,1.416305,1.084965,-0.068213,32.624613,16.690600
5,ridge_alpha_1,val,1.418588,1.087659,-0.071660,32.573997,16.685407
6,dummy_median,val,1.736167,1.607452,-0.605193,30.561288,19.090106